# Generated by Django 4.2.27 on 2025-12-31 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Couleur')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
            ],
            options={
                'verbose_name': "Catégorie d'événement",
                'verbose_name_plural': "Catégories d'événements",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('all_day', models.BooleanField(default=False, verbose_name='Toute la journée')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('recurrence', models.CharField(choices=[('none', 'Aucune'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('biweekly', 'Bihebdomadaire'), ('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='none', max_length=15, verbose_name='Récurrence')),
                ('recurrence_end_date', models.DateField(blank=True, null=True, verbose_name='Fin de récurrence')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members', 'Membres uniquement'), ('private', 'Privé')], default='public', max_length=10, verbose_name='Visibilité')),
                ('notify_before', models.PositiveIntegerField(default=1, help_text="Nombre de jours avant l'événement pour envoyer une notification", verbose_name='Notification (jours avant)')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Annulé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory', verbose_name='Catégorie')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='departments.department', verbose_name='Département')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='groups.group', verbose_name='Groupe')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Événement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
