# Generated by Django 4.2.27 on 2025-12-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification_scope',
            field=models.CharField(choices=[('none', 'Aucune notification'), ('organizer', 'Organisateur uniquement'), ('group', 'Groupe concerné'), ('department', 'Département concerné'), ('members', 'Tous les membres'), ('all', 'Tout le monde')], default='none', help_text='Qui doit recevoir les notifications pour cet événement', max_length=15, verbose_name='Portée des notifications'),
        ),
        migrations.AddField(
            model_name='event',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Notification envoyée'),
        ),
    ]
