# Generated by Django 4.2.27 on 2026-01-01 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_event_notification_scope_event_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Aucune'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('biweekly', 'Bihebdomadaire'), ('monthly', 'Mensuel'), ('trimesterly', 'Trimestriel'), ('yearly', 'Annuel')], default='none', max_length=15, verbose_name='Récurrence'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(blank=True, null=True, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur'),
        ),
    ]
