# Generated by Django 4.2.27 on 2026-01-01 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_remove_event_organizer_alter_event_recurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, null=True, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('members', 'Membres uniquement'), ('private', 'Privé')], default='public', max_length=20, verbose_name='Visibilité'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events_single', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
