# Generated by Django 4.2.27 on 2026-01-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_organizers_remove_event_organizer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
