# Generated by Django 5.2.9 on 2026-01-02 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_core'),
        ('events', '0005_remove_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour un événement global', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.site', verbose_name='Site'),
        ),
    ]
