# Generated by Django 4.2.27 on 2026-02-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventcategory_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='event_start_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'start_time'], name='event_start_datetime_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['site'], name='event_site_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['visibility'], name='event_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_cancelled'], name='event_cancelled_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='event_category_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['site', 'start_date'], name='event_site_date_idx'),
        ),
    ]
