# Generated by Django 4.2.27 on 2025-12-31 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la tranche')),
                ('min_age', models.PositiveIntegerField(verbose_name='Âge minimum')),
                ('max_age', models.PositiveIntegerField(verbose_name='Âge maximum')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': "Tranche d'âge",
                'verbose_name_plural': "Tranches d'âge",
                'ordering': ['min_age'],
            },
        ),
        migrations.CreateModel(
            name='BibleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Salle')),
                ('max_capacity', models.PositiveIntegerField(default=15, verbose_name='Capacité max')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='bibleclub.agegroup', verbose_name="Tranche d'âge")),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['age_group__min_age'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bibleclub/children/', verbose_name='Photo')),
                ('parent1_name', models.CharField(max_length=200, verbose_name='Parent 1 - Nom')),
                ('parent1_phone', models.CharField(max_length=20, verbose_name='Parent 1 - Téléphone')),
                ('parent1_email', models.EmailField(blank=True, max_length=254, verbose_name='Parent 1 - Email')),
                ('parent2_name', models.CharField(blank=True, max_length=200, verbose_name='Parent 2 - Nom')),
                ('parent2_phone', models.CharField(blank=True, max_length=20, verbose_name='Parent 2 - Téléphone')),
                ('emergency_contact', models.CharField(blank=True, max_length=200, verbose_name="Contact d'urgence")),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name="Téléphone d'urgence")),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('medical_notes', models.TextField(blank=True, verbose_name='Notes médicales')),
                ('needs_transport', models.BooleanField(default=False, verbose_name='Besoin de transport')),
                ('pickup_address', models.TextField(blank=True, verbose_name='Adresse de ramassage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_children', to='transport.driverprofile', verbose_name='Chauffeur assigné')),
                ('bible_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='bibleclub.bibleclass', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('theme', models.CharField(blank=True, max_length=200, verbose_name='Thème')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Annulée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lead', models.BooleanField(default=False, verbose_name='Moniteur principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bible_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitors', to='bibleclub.bibleclass', verbose_name='Classe assignée')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Moniteur',
                'verbose_name_plural': 'Moniteurs',
                'ordering': ['-is_lead', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='DriverCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée église")),
                ('return_departure_time', models.TimeField(blank=True, null=True, verbose_name='Heure départ retour')),
                ('return_arrival_time', models.TimeField(blank=True, null=True, verbose_name='Heure arrivée retour')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('children_picked_up', models.ManyToManyField(blank=True, related_name='transport_pickups', to='bibleclub.child', verbose_name='Enfants transportés')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='transport.driverprofile', verbose_name='Chauffeur')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_checkins', to='bibleclub.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Pointage Chauffeur',
                'verbose_name_plural': 'Pointages Chauffeurs',
                'unique_together': {('session', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('absent_notified', 'Absent (notifié)'), ('late', 'En retard'), ('excused', 'Excusé')], default='absent', max_length=20, verbose_name='Statut')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('picked_up_by', models.CharField(blank=True, max_length=200, verbose_name='Récupéré par')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bible_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='bibleclub.bibleclass', verbose_name='Classe')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='bibleclub.child', verbose_name='Enfant')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='bibleclub.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['child__last_name', 'child__first_name'],
                'unique_together': {('session', 'child')},
            },
        ),
    ]
