# Generated by Django 5.2.9 on 2025-12-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleclub', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: None,  # Migration vide pour éviter les conflits
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
