# Generated by Django 5.2.9 on 2025-12-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleclub', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agegroup',
            constraint=models.CheckConstraint(check=models.Q(('min_age__lt', models.F('max_age'))), name='min_age_less_than_max_age'),
        ),
    ]
