# Generated by Django 4.2.27 on 2026-01-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleclub', '0002_add_age_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent1_email',
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent1_name',
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent1_phone',
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent2_name',
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent2_phone',
        ),
        migrations.AddField(
            model_name='child',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du père'),
        ),
        migrations.AddField(
            model_name='child',
            name='father_name',
            field=models.CharField(default='papa', max_length=200, verbose_name='Nom du père'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='father_phone',
            field=models.CharField(default='0694000000', max_length=20, verbose_name='Téléphone du père'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de la mère'),
        ),
        migrations.AddField(
            model_name='child',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom de la mère'),
        ),
        migrations.AddField(
            model_name='child',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone de la mère'),
        ),
    ]
