# Generated by Django 4.2.27 on 2026-01-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleclub', '0003_remove_child_parent1_email_remove_child_parent1_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agegroup',
            constraint=models.CheckConstraint(check=models.Q(('min_age__lt', models.F('max_age'))), name='min_age_less_than_max_age'),
        ),
    ]
