# Generated by Django 4.2.27 on 2026-05-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleclub', '0005_child_linked_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse postale'),
        ),
        migrations.AddField(
            model_name='child',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='child',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code postal'),
        ),
    ]
