# Generated by Django 4.2.27 on 2026-05-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleclub', '0006_child_address_child_city_child_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du père'),
        ),
        migrations.AlterField(
            model_name='child',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du père'),
        ),
    ]
