# Generated by Django 5.2.9 on 2026-01-01 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('naissance', 'Naissance'), ('deces', 'Décès'), ('mariage', 'Mariage'), ('bapteme', 'Baptême'), ('hospitalisation', 'Hospitalisation'), ('deuil', 'Deuil (proche)'), ('conversion', 'Conversion'), ('anniversaire_mariage', 'Anniversaire de mariage'), ('autre', 'Autre')], max_length=25, verbose_name="Type d'événement")),
                ('event_date', models.DateField(verbose_name="Date de l'événement")),
                ('title', models.CharField(blank=True, help_text="Ex: 'Naissance de Paul', 'Mariage Jean & Marie'", max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority', models.CharField(choices=[('haute', 'Haute'), ('normale', 'Normale'), ('basse', 'Basse')], default='normale', max_length=10, verbose_name='Priorité')),
                ('requires_visit', models.BooleanField(default=True, help_text='Cocher si une visite pastorale est nécessaire', verbose_name='Visite requise')),
                ('visit_completed', models.BooleanField(default=False, verbose_name='Visite effectuée')),
                ('announce_sunday', models.BooleanField(default=False, help_text='À annoncer lors du culte', verbose_name='Annoncer dimanche')),
                ('announced', models.BooleanField(default=False, verbose_name='Annoncé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes pastorales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_events', to='members.member', verbose_name='Membre principal')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_life_events', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('related_members', models.ManyToManyField(blank=True, help_text='Autres membres concernés (conjoint, famille...)', related_name='related_life_events', to='members.member', verbose_name='Membres liés')),
            ],
            options={
                'verbose_name': 'Événement de vie',
                'verbose_name_plural': 'Événements de vie',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('domicile', 'Visite à domicile'), ('hopital', "Visite à l'hôpital"), ('zoom', 'Appel vidéo (Zoom/WhatsApp)'), ('telephone', 'Appel téléphonique'), ('bureau', 'Rencontre au bureau'), ('autre', 'Autre')], default='domicile', max_length=15, verbose_name='Type de visite')),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('a_faire', 'À faire'), ('effectue', 'Effectué'), ('annule', 'Annulé'), ('reporte', 'Reporté')], default='planifie', max_length=15, verbose_name='Statut')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Date effective')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (minutes)')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé de la visite')),
                ('prayer_requests', models.TextField(blank=True, verbose_name='Sujets de prière')),
                ('follow_up_needed', models.BooleanField(default=False, verbose_name='Suivi nécessaire')),
                ('follow_up_notes', models.TextField(blank=True, verbose_name='Notes de suivi')),
                ('is_confidential', models.BooleanField(default=False, help_text='Visible uniquement par le pasteur principal', verbose_name='Confidentiel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('life_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='members.lifeevent', verbose_name='Événement lié')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits_received', to='members.member', verbose_name='Membre visité')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_made', to=settings.AUTH_USER_MODEL, verbose_name='Visiteur')),
            ],
            options={
                'verbose_name': 'Visite pastorale',
                'verbose_name_plural': 'Visites pastorales',
                'ordering': ['-visit_date', '-scheduled_date'],
            },
        ),
    ]
