# Generated by Django 5.2.9 on 2026-01-02 00:06

import django.db.models.deletion
from django.db import migrations, models
import random
import string


def generate_member_ids(apps, schema_editor):
    """Génère des IDs uniques pour les membres existants."""
    Member = apps.get_model('members', 'Member')
    
    used_ids = set()
    
    for member in Member.objects.all():
        # Générer un ID unique
        while True:
            random_suffix = ''.join(random.choices(string.digits, k=4))
            new_id = f"EEBC-CAB-{random_suffix}"  # Par défaut Cabassou
            
            if new_id not in used_ids:
                used_ids.add(new_id)
                member.member_id = new_id
                member.save(update_fields=['member_id'])
                break


def reverse_member_ids(apps, schema_editor):
    """Reverse migration - ne fait rien."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_core'),
        ('members', '0002_lifeevent_visitationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de décès'),
        ),
        migrations.AddField(
            model_name='member',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.family', verbose_name='Famille'),
        ),
        migrations.AddField(
            model_name='member',
            name='family_role',
            field=models.CharField(blank=True, choices=[('HEAD', 'Chef de famille'), ('SPOUSE', 'Conjoint(e)'), ('CHILD', 'Enfant'), ('PARENT', 'Parent'), ('OTHER', 'Autre')], max_length=10, verbose_name='Rôle dans la famille'),
        ),
        # Ajouter le champ member_id sans contrainte unique d'abord
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, max_length=15, verbose_name='ID Membre'),
        ),
        migrations.AddField(
            model_name='member',
            name='notify_by_email',
            field=models.BooleanField(default=True, verbose_name='Notifier par email'),
        ),
        migrations.AddField(
            model_name='member',
            name='notify_by_sms',
            field=models.BooleanField(default=False, verbose_name='Notifier par SMS'),
        ),
        migrations.AddField(
            model_name='member',
            name='notify_by_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Notifier par WhatsApp'),
        ),
        migrations.AddField(
            model_name='member',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='member',
            name='wedding_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de mariage'),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro WhatsApp'),
        ),
        # Générer les IDs pour les membres existants
        migrations.RunPython(generate_member_ids, reverse_member_ids),
        # Maintenant ajouter la contrainte unique
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, help_text='Généré automatiquement : EEBC-CAB-XXXX ou EEBC-MAC-XXXX', max_length=15, unique=True, verbose_name='ID Membre'),
        ),
    ]
