# Generated by Django 4.2.27 on 2026-02-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_initial_core'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lifeevent',
            index=models.Index(fields=['event_date'], name='lifeevent_date_idx'),
        ),
        migrations.AddIndex(
            model_name='lifeevent',
            index=models.Index(fields=['event_type'], name='lifeevent_type_idx'),
        ),
        migrations.AddIndex(
            model_name='lifeevent',
            index=models.Index(fields=['primary_member'], name='lifeevent_member_idx'),
        ),
        migrations.AddIndex(
            model_name='lifeevent',
            index=models.Index(fields=['requires_visit', 'visit_completed'], name='lifeevent_visit_idx'),
        ),
        migrations.AddIndex(
            model_name='lifeevent',
            index=models.Index(fields=['announce_sunday', 'announced'], name='lifeevent_announce_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status'], name='member_status_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['site'], name='member_site_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['date_joined'], name='member_date_joined_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['is_baptized'], name='member_baptized_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['family'], name='member_family_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status', 'site'], name='member_status_site_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name', 'first_name'], name='member_name_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['email'], name='member_email_idx'),
        ),
        migrations.AddIndex(
            model_name='visitationlog',
            index=models.Index(fields=['visit_date'], name='visitlog_visitdate_idx'),
        ),
        migrations.AddIndex(
            model_name='visitationlog',
            index=models.Index(fields=['scheduled_date'], name='visitlog_scheddate_idx'),
        ),
        migrations.AddIndex(
            model_name='visitationlog',
            index=models.Index(fields=['member'], name='visitlog_member_idx'),
        ),
        migrations.AddIndex(
            model_name='visitationlog',
            index=models.Index(fields=['visitor'], name='visitlog_visitor_idx'),
        ),
        migrations.AddIndex(
            model_name='visitationlog',
            index=models.Index(fields=['status'], name='visitlog_status_idx'),
        ),
        migrations.AddIndex(
            model_name='visitationlog',
            index=models.Index(fields=['member', 'visit_date'], name='visitlog_member_date_idx'),
        ),
    ]
