# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_lifeevent_lifeevent_date_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Clé d'adresse canonique")),
                ('normalized_address', models.TextField(blank=True, verbose_name='Adresse normalisée')),
                ('normalized_city', models.CharField(blank=True, max_length=100, verbose_name='Ville normalisée')),
                ('normalized_postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal normalisé')),
                ('country', models.CharField(default='Guyane française', max_length=100, verbose_name='Pays')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('provider', models.CharField(default='nominatim', max_length=50, verbose_name='Provider')),
                ('provider_precision', models.CharField(blank=True, max_length=50, verbose_name='Précision provider')),
                ('provider_importance', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='Importance provider')),
                ('raw_query', models.TextField(blank=True, verbose_name='Requête brute')),
                ('last_geocoded_at', models.DateTimeField(auto_now=True, verbose_name='Dernier géocodage')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adresse géocodée',
                'verbose_name_plural': 'Adresses géocodées',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='geocodedaddress',
            index=models.Index(fields=['address_key'], name='geocode_addr_key_idx'),
        ),
        migrations.AddIndex(
            model_name='geocodedaddress',
            index=models.Index(fields=['expires_at'], name='geocode_expires_idx'),
        ),
    ]
