# Generated by Django 4.2.27 on 2026-01-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('responsable_club', 'Responsable Club Biblique'), ('moniteur', 'Moniteur'), ('chauffeur', 'Chauffeur'), ('responsable_groupe', 'Responsable de Groupe'), ('secretariat', 'Secrétariat'), ('finance', 'Finance'), ('encadrant', 'Encadrant'), ('membre', 'Membre')], default='membre', max_length=20, verbose_name='Rôle'),
        ),
    ]
