# Generated by Django 5.2.9 on 2026-01-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_backup_codes',
            field=models.TextField(blank=True, help_text='Codes de secours hashés (JSON)', verbose_name='Codes de secours'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_confirmed',
            field=models.BooleanField(default=False, help_text="L'utilisateur a confirmé la configuration 2FA", verbose_name='2FA confirmé'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA activé'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='Clé TOTP pour Google Authenticator', max_length=32, verbose_name='Clé secrète 2FA'),
        ),
    ]
