# Generated by Django 5.2.9 on 2026-01-04 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_two_factor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by_team',
            field=models.BooleanField(default=False, help_text="Indique si ce compte a été créé par un membre de l'équipe", verbose_name="Créé par l'équipe"),
        ),
    ]
