# Generated by Django 5.2.9 on 2026-01-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_created_by_user_created_by_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text="Force l'utilisateur à changer son mot de passe à la prochaine connexion", verbose_name='Doit changer le mot de passe'),
        ),
    ]
