# Generated by Django 5.2.9 on 2026-01-06 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentatives de connexion échouées'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP de connexion'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Verrouillé jusqu'à"),
        ),
        migrations.CreateModel(
            name='PasswordChangeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Token de changement de mot de passe',
                'verbose_name_plural': 'Tokens de changement de mot de passe',
                'ordering': ['-created_at'],
            },
        ),
    ]
