# Generated by Django 4.2.27 on 2026-01-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_rate_limiting_and_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(default='membre', help_text='Rôles séparés par des virgules (ex: pasteur,ancien)', verbose_name='Rôles'),
        ),
    ]
