# Generated by Django 5.2.9 on 2026-01-01 23:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_remove_event_organizer'),
        ('members', '0002_lifeevent_visitationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('service_type', models.CharField(choices=[('culte_dominical', 'Culte dominical'), ('culte_semaine', 'Culte de semaine'), ('sainte_cene', 'Sainte Cène'), ('bapteme', 'Service de baptême'), ('mariage', 'Cérémonie de mariage'), ('funerailles', 'Service funèbre'), ('special', 'Service spécial')], default='culte_dominical', max_length=20, verbose_name='Type de service')),
                ('estimated_duration', models.PositiveIntegerField(default=90, verbose_name='Durée estimée (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modèle de service',
                'verbose_name_plural': 'Modèles de service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('accueil', 'Accueil'), ('louange', 'Temps de louange'), ('priere', 'Prière'), ('lecture', 'Lecture biblique'), ('annonces', 'Annonces'), ('offrande', 'Offrande'), ('predication', 'Prédication'), ('appel', 'Appel'), ('sainte_cene', 'Sainte Cène'), ('bapteme', 'Baptême'), ('temoignage', 'Témoignage'), ('video', 'Vidéo/Présentation'), ('benediction', 'Bénédiction'), ('pause', 'Pause/Transition'), ('autre', 'Autre')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('duration_minutes', models.PositiveIntegerField(default=5, verbose_name='Durée (minutes)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='worship.servicetemplate', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': 'Élément de modèle',
                'verbose_name_plural': 'Éléments de modèle',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorshipService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('culte_dominical', 'Culte dominical'), ('culte_semaine', 'Culte de semaine'), ('sainte_cene', 'Sainte Cène'), ('bapteme', 'Service de baptême'), ('mariage', 'Cérémonie de mariage'), ('funerailles', 'Service funèbre'), ('special', 'Service spécial')], default='culte_dominical', max_length=20, verbose_name='Type de service')),
                ('theme', models.CharField(blank=True, max_length=200, verbose_name='Thème du culte')),
                ('bible_text', models.CharField(blank=True, help_text='Ex: Jean 3:16-21', max_length=200, verbose_name='Texte biblique')),
                ('sermon_title', models.CharField(blank=True, max_length=200, verbose_name='Titre de la prédication')),
                ('sermon_notes', models.TextField(blank=True, verbose_name='Notes de prédication')),
                ('expected_attendance', models.PositiveIntegerField(blank=True, null=True, verbose_name='Affluence prévue')),
                ('actual_attendance', models.PositiveIntegerField(blank=True, null=True, verbose_name='Affluence réelle')),
                ('offering_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total des offrandes')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Planning confirmé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes générales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worship_service', to='events.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Service de culte',
                'verbose_name_plural': 'Services de culte',
                'ordering': ['-event__start_date'],
            },
        ),
        migrations.CreateModel(
            name='ServicePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('accueil', 'Accueil'), ('louange', 'Temps de louange'), ('priere', 'Prière'), ('lecture', 'Lecture biblique'), ('annonces', 'Annonces'), ('offrande', 'Offrande'), ('predication', 'Prédication'), ('appel', 'Appel'), ('sainte_cene', 'Sainte Cène'), ('bapteme', 'Baptême'), ('temoignage', 'Témoignage'), ('video', 'Vidéo/Présentation'), ('benediction', 'Bénédiction'), ('pause', 'Pause/Transition'), ('autre', 'Autre')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre/Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('duration_minutes', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Durée (minutes)')),
                ('notes', models.TextField(blank=True, help_text="Instructions pour l'équipe technique", verbose_name='Notes')),
                ('resources_needed', models.TextField(blank=True, help_text='Micro, pupitre, écran, etc.', verbose_name='Ressources nécessaires')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_responsibilities', to='members.member', verbose_name='Responsable')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='worship.worshipservice', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Élément de programme',
                'verbose_name_plural': 'Éléments de programme',
                'ordering': ['service', 'order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('predicateur', 'Prédicateur'), ('dirigeant', 'Dirigeant de culte'), ('sonorisation', 'Sonorisation'), ('projection', 'Projection'), ('accueil', 'Accueil'), ('offrandes', 'Gestion des offrandes'), ('lecture', 'Lecture biblique'), ('priere', 'Prière'), ('annonces', 'Annonces'), ('sainte_cene', 'Service Sainte Cène'), ('enfants', 'Responsable enfants'), ('streaming', 'Streaming/Enregistrement'), ('autre', 'Autre')], max_length=20, verbose_name='Rôle')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('decline', 'Décliné'), ('remplace', 'Remplacé')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notifié le')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_roles', to='members.member', verbose_name='Membre assigné')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_roles', to='members.member', verbose_name='Remplacé par')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_roles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur assigné')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='worship.worshipservice', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Rôle de service',
                'verbose_name_plural': 'Rôles de service',
                'ordering': ['service', 'role'],
                'unique_together': {('service', 'role', 'member')},
            },
        ),
    ]
