# Generated by Django 5.2.9 on 2026-01-02 03:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_newsarticle_author_fields'),
        ('members', '0003_initial_core'),
        ('worship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerole',
            name='role',
            field=models.CharField(choices=[('predicateur', 'Prédicateur'), ('dirigeant', 'Dirigeant de culte'), ('choriste', 'Choriste'), ('musicien', 'Musicien'), ('chef_chorale', 'Chef de chorale'), ('sonorisation', 'Sonorisation'), ('projection', 'Projection'), ('accueil', 'Accueil'), ('offrandes', 'Gestion des offrandes'), ('lecture', 'Lecture biblique'), ('priere', 'Prière'), ('annonces', 'Annonces'), ('sainte_cene', 'Service Sainte Cène'), ('enfants', 'Responsable enfants'), ('streaming', 'Streaming/Enregistrement'), ('autre', 'Autre')], max_length=20, verbose_name='Rôle'),
        ),
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours de validation'), ('valide', 'Validé'), ('publie', 'Publié')], default='brouillon', max_length=15, verbose_name='Statut')),
                ('notification_day', models.PositiveIntegerField(default=3, help_text='0=Lundi, 1=Mardi, 2=Mercredi, 3=Jeudi, 4=Vendredi, 5=Samedi, 6=Dimanche', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Jour de notification')),
                ('days_before_service', models.PositiveIntegerField(default=4, help_text='Nombre de jours avant le culte pour envoyer la notification', verbose_name='Jours avant le culte')),
                ('notify_by_email', models.BooleanField(default=True, verbose_name='Notifier par email')),
                ('notify_by_sms', models.BooleanField(default=False, verbose_name='Notifier par SMS')),
                ('notify_by_whatsapp', models.BooleanField(default=False, verbose_name='Notifier par WhatsApp')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_schedules', to='core.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Planning mensuel',
                'verbose_name_plural': 'Plannings mensuels',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month', 'site')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(default='09:30', verbose_name='Heure de début')),
                ('theme', models.CharField(blank=True, max_length=200, verbose_name='Thème')),
                ('bible_text', models.CharField(blank=True, max_length=200, verbose_name='Texte biblique')),
                ('notifications_sent', models.BooleanField(default=False, verbose_name='Notifications envoyées')),
                ('notifications_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('choir_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choir_led_services', to='members.member', verbose_name='Chef de chorale')),
                ('musicians', models.ManyToManyField(blank=True, related_name='musician_services', to='members.member', verbose_name='Musiciens')),
                ('preacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preaching_services', to='members.member', verbose_name='Prédicateur')),
                ('projection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projection_services', to='members.member', verbose_name='Projection')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='worship.monthlyschedule', verbose_name='Planning')),
                ('singers', models.ManyToManyField(blank=True, related_name='singing_services', to='members.member', verbose_name='Choristes')),
                ('sound_tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sound_services', to='members.member', verbose_name='Sonorisation')),
                ('worship_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_services', to='members.member', verbose_name='Dirigeant')),
            ],
            options={
                'verbose_name': 'Culte programmé',
                'verbose_name_plural': 'Cultes programmés',
                'ordering': ['date'],
                'unique_together': {('schedule', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ServiceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name="Date d'envoi prévue")),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('notify_whatsapp', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=15, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='worship.scheduledservice', verbose_name='Culte')),
            ],
            options={
                'verbose_name': 'Notification de culte',
                'verbose_name_plural': 'Notifications de culte',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
