# Generated by Django 5.2.9 on 2026-01-02 04:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_initial_core'),
        ('worship', '0002_alter_servicerole_role_monthlyschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('preacher', 'Prédicateur'), ('worship_leader', 'Dirigeant de culte'), ('choir_leader', 'Chef de chorale'), ('singer', 'Choriste'), ('musician', 'Musicien'), ('sound_tech', 'Sonorisation'), ('projection', 'Projection')], max_length=20, verbose_name='Rôle')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('expired', 'Expiré')], default='pending', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notifié le')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('decline_reason', models.TextField(blank=True, verbose_name='Raison du refus')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='members.member', verbose_name='Membre')),
                ('scheduled_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='worship.scheduledservice', verbose_name='Culte')),
                ('suggested_replacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_as_replacement', to='members.member', verbose_name='Remplacement suggéré')),
            ],
            options={
                'verbose_name': 'Assignation de rôle',
                'verbose_name_plural': 'Assignations de rôles',
                'ordering': ['scheduled_service__date', 'role'],
                'unique_together': {('scheduled_service', 'member', 'role')},
            },
        ),
    ]
