# Generated by Django 4.2.27 on 2026-02-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0003_roleassignment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='monthlyschedule',
            index=models.Index(fields=['year', 'month'], name='schedule_year_month_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyschedule',
            index=models.Index(fields=['site'], name='schedule_site_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyschedule',
            index=models.Index(fields=['status'], name='schedule_status_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyschedule',
            index=models.Index(fields=['site', 'year', 'month'], name='schedule_site_ym_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledservice',
            index=models.Index(fields=['date'], name='schedservice_date_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledservice',
            index=models.Index(fields=['schedule'], name='schedservice_schedule_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledservice',
            index=models.Index(fields=['schedule', 'date'], name='schedservice_sched_date_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledservice',
            index=models.Index(fields=['notifications_sent'], name='schedservice_notif_idx'),
        ),
        migrations.AddIndex(
            model_name='worshipservice',
            index=models.Index(fields=['event'], name='worship_event_idx'),
        ),
        migrations.AddIndex(
            model_name='worshipservice',
            index=models.Index(fields=['service_type'], name='worship_type_idx'),
        ),
        migrations.AddIndex(
            model_name='worshipservice',
            index=models.Index(fields=['is_confirmed'], name='worship_confirmed_idx'),
        ),
    ]
