# Generated by Django 5.2.9 on 2026-01-02 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('core', '0001_initial_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour une campagne globale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='core.site', verbose_name='Site'),
        ),
    ]
