# Generated by Django 4.2.27 on 2026-02-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_add_site_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Annulé'),
        ),
    ]
