# Generated by Django 5.2.12 on 2026-04-26 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_donation_is_cancelled'),
        ('groups', '0004_groupmeeting_grp_meeting_date_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='notification_scope',
            field=models.CharField(choices=[('none', 'Aucune notification'), ('all', 'Tout le monde'), ('members', 'Tous les membres'), ('staff', 'Direction (pasteurs, diacres, anciens)'), ('group', 'Un groupe spécifique')], default='members', help_text='Qui doit être notifié de cette campagne', max_length=15, verbose_name='Portée des notifications'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Notification envoyée'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_group',
            field=models.ForeignKey(blank=True, help_text="Requis si la portée est 'Un groupe spécifique'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_campaigns', to='groups.group', verbose_name='Groupe cible'),
        ),
    ]
