# Generated by Django 5.2.12 on 2026-04-26 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_add_notification_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_person',
            field=models.ForeignKey(blank=True, help_text='Si vide, le créateur (responsable) sera notifié', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Personne à notifier'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='notification_scope',
            field=models.CharField(choices=[('none', 'Aucune notification'), ('creator', 'Créateur / personne sélectionnée'), ('staff', 'Direction (pasteurs, diacres, anciens)'), ('members', 'Tous les membres'), ('group', 'Un groupe spécifique'), ('all', 'Tout le monde')], default='members', help_text='Qui doit être notifié de cette campagne', max_length=15, verbose_name='Portée des notifications'),
        ),
    ]
