# Generated by Django 5.2.9 on 2026-01-01 23:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_remove_event_organizer'),
        ('members', '0002_lifeevent_visitationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_income', models.BooleanField(default=False, help_text="Cocher si cette catégorie concerne des entrées d'argent", verbose_name='Catégorie de revenus')),
                ('budget_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget annuel prévu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='finance.financecategory', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie financière',
                'verbose_name_plural': 'Catégories financières',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Générée automatiquement si vide', max_length=50, unique=True, verbose_name='Référence')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (€)')),
                ('transaction_type', models.CharField(choices=[('don', 'Don'), ('dime', 'Dîme'), ('offrande', 'Offrande'), ('depense', 'Dépense'), ('remboursement', 'Remboursement'), ('transfert', 'Transfert')], max_length=20, verbose_name='Type de transaction')),
                ('payment_method', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire'), ('carte', 'Carte bancaire'), ('mobile', 'Paiement mobile'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='Méthode de paiement')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('transaction_date', models.DateField(verbose_name='Date de transaction')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.financecategory', verbose_name='Catégorie')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='events.event', verbose_name='Événement lié')),
                ('member', models.ForeignKey(blank=True, help_text='Pour les dons/dîmes nominatifs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='members.member', verbose_name='Membre concerné')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('recu', 'Reçu'), ('facture', 'Facture'), ('ticket', 'Ticket de caisse'), ('releve', 'Relevé bancaire'), ('autre', 'Autre document')], default='recu', max_length=20, verbose_name='Type de document')),
                ('image', models.ImageField(upload_to='finance/proofs/%Y/%m/', verbose_name='Image du justificatif')),
                ('ocr_status', models.CharField(choices=[('non_traite', 'Non traité'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('echec', 'Échec')], default='non_traite', max_length=15, verbose_name='Statut OCR')),
                ('ocr_raw_text', models.TextField(blank=True, help_text="Texte extrait automatiquement de l'image", verbose_name='Texte OCR brut')),
                ('ocr_extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant extrait (OCR)')),
                ('ocr_extracted_date', models.DateField(blank=True, null=True, verbose_name='Date extraite (OCR)')),
                ('ocr_confidence', models.FloatField(blank=True, help_text="Score de confiance de l'extraction", null=True, verbose_name='Confiance OCR (%)')),
                ('ocr_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='finance.financialtransaction', verbose_name='Transaction')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_proofs', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Preuve de paiement',
                'verbose_name_plural': 'Preuves de paiement',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('month', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour un budget annuel', null=True, verbose_name='Mois')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant prévu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='finance.financecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Ligne budgétaire',
                'verbose_name_plural': 'Lignes budgétaires',
                'ordering': ['-year', 'month', 'category__name'],
                'unique_together': {('category', 'year', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_date'], name='finance_fin_transac_36d0df_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_type'], name='finance_fin_transac_ef0571_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['status'], name='finance_fin_status_26c0e3_idx'),
        ),
    ]
