# Generated by Django 5.2.9 on 2026-01-02 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_core'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.site', verbose_name='Site'),
        ),
    ]
