# Generated by Django 5.2.9 on 2026-01-02 02:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_newsarticle_author_fields'),
        ('finance', '0002_add_site_field'),
        ('members', '0003_initial_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(max_length=255, unique=True, verbose_name='ID Session Stripe')),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, verbose_name='ID Payment Intent')),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Pour les dons récurrents', max_length=255, verbose_name='ID Abonnement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Montant (€)')),
                ('donation_type', models.CharField(choices=[('don', 'Don'), ('dime', 'Dîme'), ('offrande', 'Offrande')], default='don', max_length=20, verbose_name='Type de don')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Don récurrent')),
                ('recurring_interval', models.CharField(blank=True, choices=[('month', 'Mensuel'), ('year', 'Annuel')], max_length=10, verbose_name='Fréquence')),
                ('donor_email', models.EmailField(max_length=254, verbose_name='Email du donateur')),
                ('donor_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du donateur')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_donations', to='members.member', verbose_name='Membre')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_donations', to='core.site', verbose_name='Site')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_donation', to='finance.financialtransaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Don en ligne',
                'verbose_name_plural': 'Dons en ligne',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de reçu')),
                ('fiscal_year', models.PositiveIntegerField(verbose_name='Année fiscale')),
                ('donor_name', models.CharField(max_length=200, verbose_name='Nom du donateur')),
                ('donor_address', models.TextField(verbose_name='Adresse du donateur')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émis'), ('sent', 'Envoyé'), ('cancelled', 'Annulé')], default='draft', max_length=15, verbose_name='Statut')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='finance/tax_receipts/%Y/', verbose_name='Fichier PDF')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('sent_date', models.DateField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tax_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Émis par')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_receipts', to='members.member', verbose_name='Membre')),
                ('transactions', models.ManyToManyField(related_name='tax_receipts', to='finance.financialtransaction', verbose_name='Transactions')),
            ],
            options={
                'verbose_name': 'Reçu fiscal',
                'verbose_name_plural': 'Reçus fiscaux',
                'ordering': ['-fiscal_year', '-receipt_number'],
            },
        ),
    ]
