# Generated by Django 5.2.9 on 2026-01-05 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_budgetcategory_budget_budgetitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='approval_comments',
            field=models.TextField(blank=True, verbose_name="Commentaires d'approbation"),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('partially_approved', 'Partiellement approuvé')], default='pending', max_length=20, verbose_name="Statut d'approbation"),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_items', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motif de refus'),
        ),
    ]
