# Generated by Django 4.2.27 on 2026-02-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_soft_delete'),
        ('finance', '0005_budgetitem_approval_comments_and_more'),
    ]

    operations = [
    ]
