# Generated by Django 4.2.27 on 2026-02-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_merge_20260214_0936'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='financialtransaction',
            name='financial_deleted_status_idx',
        ),
        migrations.RenameIndex(
            model_name='financialtransaction',
            new_name='fin_trans_date_idx',
            old_name='finance_fin_transac_36d0df_idx',
        ),
        migrations.RenameIndex(
            model_name='financialtransaction',
            new_name='fin_trans_type_idx',
            old_name='finance_fin_transac_ef0571_idx',
        ),
        migrations.RenameIndex(
            model_name='financialtransaction',
            new_name='fin_trans_status_idx',
            old_name='finance_fin_status_26c0e3_idx',
        ),
        migrations.RenameIndex(
            model_name='financialtransaction',
            new_name='fin_trans_deleted_idx',
            old_name='financial_deleted_idx',
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Soft-delete : les données restent en BD pour l'audit", verbose_name='Supprimé'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['year'], name='budgetline_year_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['category'], name='budgetline_category_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['year', 'month'], name='budgetline_year_month_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['member'], name='fin_trans_member_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['category'], name='fin_trans_category_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_date', 'status'], name='fin_trans_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['member', 'transaction_date'], name='fin_trans_memb_date_idx'),
        ),
    ]
