# Generated by Django 5.2.12 on 2026-04-17 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_financialtransaction_financial_deleted_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du prévisionnel')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('scenario', models.CharField(choices=[('realiste', 'Réaliste'), ('optimiste', 'Optimiste'), ('pessimiste', 'Pessimiste')], default='realiste', max_length=15, verbose_name='Scénario')),
                ('description', models.TextField(blank=True, verbose_name='Description / hypothèses')),
                ('is_active', models.BooleanField(default=True, help_text='Un seul prévisionnel actif par année et scénario', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forecasts', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Prévisionnel budgétaire',
                'verbose_name_plural': 'Prévisionnels budgétaires',
                'ordering': ['-year', 'scenario'],
                'unique_together': {('year', 'scenario')},
            },
        ),
        migrations.CreateModel(
            name='ForecastLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('line_type', models.CharField(choices=[('income', 'Recette'), ('expense', 'Dépense')], max_length=10, verbose_name='Type')),
                ('jan', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Janvier')),
                ('feb', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Février')),
                ('mar', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mars')),
                ('apr', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Avril')),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mai')),
                ('jun', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Juin')),
                ('jul', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Juillet')),
                ('aug', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Août')),
                ('sep', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Septembre')),
                ('oct', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Octobre')),
                ('nov', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Novembre')),
                ('dec', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Décembre')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_lines', to='finance.financecategory', verbose_name='Catégorie financière')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.budgetforecast', verbose_name='Prévisionnel')),
            ],
            options={
                'verbose_name': 'Ligne de prévisionnel',
                'verbose_name_plural': 'Lignes de prévisionnel',
                'ordering': ['line_type', 'label'],
            },
        ),
    ]
