# Generated by Django 5.2.9 on 2026-01-02 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_lifeevent_visitationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('estimated_population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Population estimée')),
                ('last_census_date', models.DateField(blank=True, null=True, verbose_name='Dernier recensement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='core.city', verbose_name='Ville')),
                ('zone_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_neighborhoods', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de zone')),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['city__name', 'name'],
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('CAB', 'Cabassou (Cayenne)'), ('MAC', 'Macouria')], max_length=3, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('worship_schedule', models.TextField(blank=True, help_text='Ex: Dimanche 9h et 11h', verbose_name='Horaires des cultes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_main_site', models.BooleanField(default=False, help_text='Le site principal pour les vues consolidées', verbose_name='Site principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administrators', models.ManyToManyField(blank=True, related_name='administered_sites', to=settings.AUTH_USER_MODEL, verbose_name='Administrateurs')),
                ('pastor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastored_sites', to=settings.AUTH_USER_MODEL, verbose_name='Pasteur')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['-is_main_site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MissionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='planned', max_length=15, verbose_name='Statut')),
                ('homes_visited', models.PositiveIntegerField(default=0, verbose_name='Foyers visités')),
                ('contacts_made', models.PositiveIntegerField(default=0, verbose_name='Contacts établis')),
                ('decisions_made', models.PositiveIntegerField(default=0, verbose_name='Décisions')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_missions', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('team_members', models.ManyToManyField(blank=True, related_name='mission_participations', to='members.member', verbose_name='Équipe')),
                ('neighborhoods', models.ManyToManyField(related_name='mission_campaigns', to='core.neighborhood', verbose_name='Quartiers ciblés')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_campaigns', to='core.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Campagne de mission',
                'verbose_name_plural': 'Campagnes de mission',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Famille DUPONT', max_length=100, verbose_name='Nom de famille')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='core.neighborhood', verbose_name='Quartier')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='core.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('spouse', 'Conjoint(e)'), ('parent', 'Parent'), ('child', 'Enfant'), ('sibling', 'Frère/Sœur'), ('grandparent', 'Grand-parent'), ('grandchild', 'Petit-enfant'), ('uncle_aunt', 'Oncle/Tante'), ('nephew_niece', 'Neveu/Nièce'), ('cousin', 'Cousin(e)'), ('in_law', 'Beau-parent/Belle-famille'), ('other', 'Autre')], max_length=15, verbose_name='Type de relation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='members.member', verbose_name='Membre')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='members.member', verbose_name='Lié à')),
            ],
            options={
                'verbose_name': 'Relation familiale',
                'verbose_name_plural': 'Relations familiales',
                'unique_together': {('from_member', 'to_member')},
            },
        ),
    ]
