# Generated by Django 5.2.9 on 2026-01-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(help_text='Code court unique (ex: CAB, MAC). Utilisé pour générer les IDs membres.', max_length=5, unique=True, verbose_name='Code'),
        ),
    ]
