# Generated by Django 5.2.9 on 2026-01-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_public_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('news', 'Actualité'), ('announcement', 'Annonce'), ('testimony', 'Témoignage'), ('devotional', 'Méditation')], default='news', max_length=20, verbose_name='Catégorie'),
        ),
    ]
