# Generated by Django 5.2.9 on 2026-01-02 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_event_recap_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='author_name',
            field=models.CharField(blank=True, help_text='Requis pour les méditations', max_length=100, verbose_name="Nom de l'auteur"),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='display_end_date',
            field=models.DateField(blank=True, help_text="Date jusqu'à laquelle l'article est affiché (optionnel)", null=True, verbose_name="Fin d'affichage"),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='display_start_date',
            field=models.DateField(blank=True, help_text="Date à partir de laquelle l'article est affiché (optionnel)", null=True, verbose_name="Début d'affichage"),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.ForeignKey(blank=True, help_text="Utilisateur interne qui a créé l'article", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteur (utilisateur)'),
        ),
    ]
