# Generated by Django 5.2.9 on 2026-01-06 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_newsarticle_author_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('login_failed', 'Échec connexion'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('export', 'Export'), ('access_denied', 'Accès refusé'), ('view', 'Consultation')], max_length=20, verbose_name='Action')),
                ('model_name', models.CharField(blank=True, help_text='Nom du modèle concerné (ex: Member, FinancialTransaction)', max_length=100, verbose_name='Modèle')),
                ('object_id', models.CharField(blank=True, help_text="Identifiant de l'objet concerné", max_length=50, verbose_name='ID Objet')),
                ('object_repr', models.CharField(blank=True, help_text="Représentation textuelle de l'objet", max_length=200, verbose_name='Représentation')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Détails des modifications (ancien/nouveau)', verbose_name='Changements')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('path', models.CharField(blank=True, help_text='URL de la requête', max_length=500, verbose_name='Chemin URL')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Informations additionnelles contextuelles', verbose_name='Données supplémentaires')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'), models.Index(fields=['action', '-timestamp'], name='core_auditl_action_f07419_idx'), models.Index(fields=['model_name', '-timestamp'], name='core_auditl_model_n_9470ca_idx'), models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx')],
            },
        ),
    ]
