# Generated by Django 5.2.9 on 2026-01-06 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_auditlog_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Nom du fichier de sauvegarde', max_length=255, verbose_name='Nom du fichier')),
                ('file_path', models.CharField(help_text='Chemin complet vers le fichier de sauvegarde', max_length=500, verbose_name='Chemin du fichier')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('status', models.CharField(choices=[('pending', 'En cours'), ('success', 'Réussie'), ('failed', 'Échouée')], default='pending', max_length=10, verbose_name='Statut')),
                ('database_engine', models.CharField(blank=True, help_text='Type de base de données (SQLite, PostgreSQL, MySQL)', max_length=50, verbose_name='Moteur de base de données')),
                ('backup_type', models.CharField(choices=[('automatic', 'Automatique'), ('manual', 'Manuelle')], default='automatic', max_length=20, verbose_name='Type de sauvegarde')),
                ('celery_task_id', models.CharField(blank=True, help_text='Identifiant de la tâche Celery ayant créé cette sauvegarde', max_length=255, verbose_name='ID de tâche Celery')),
                ('error_message', models.TextField(blank=True, help_text="Détails de l'erreur en cas d'échec", verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant déclenché la sauvegarde (pour les sauvegardes manuelles)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Sauvegarde de base de données',
                'verbose_name_plural': 'Sauvegardes de base de données',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_databa_created_64916d_idx'), models.Index(fields=['status', '-created_at'], name='core_databa_status_94c466_idx')],
            },
        ),
    ]
