# Generated by Django 5.2.9 on 2026-01-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_databasebackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('login_failed', 'Échec connexion'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('export', 'Export'), ('access_denied', 'Accès refusé'), ('view', 'Consultation'), ('server_error', 'Erreur serveur')], max_length=20, verbose_name='Action'),
        ),
    ]
