# Generated by Django 4.2.27 on 2026-02-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_worshipschedule_testimony'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['publish_date'], name='article_pubdate_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['is_published'], name='article_published_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['is_featured'], name='article_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['category'], name='article_category_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['is_published', '-publish_date'], name='article_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['code'], name='site_code_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['is_active'], name='site_active_idx'),
        ),
    ]
