# Generated by Django 4.2.27 on 2026-04-18 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_geocodedaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='Type MIME')),
                ('media_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Vidéo')], default='document', max_length=10, verbose_name='Type de média')),
                ('source', models.CharField(choices=[('manual', 'Import manuel'), ('generated', 'Généré par le système'), ('import', 'Import en masse'), ('scan', 'Numérisation'), ('recording', 'Enregistrement')], default='manual', max_length=15, verbose_name='Source')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags (séparés par des virgules)')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Confidentiel')),
                ('linked_app', models.CharField(blank=True, max_length=50, verbose_name='Application liée')),
                ('linked_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet lié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='bi-folder', max_length=50, verbose_name='Icône Bootstrap')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Couleur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de document',
                'verbose_name_plural': 'Catégories de documents',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email destinataire')),
                ('recipient_name', models.CharField(blank=True, max_length=150, verbose_name='Nom destinataire')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Consulté le')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document', verbose_name='Document')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_shares', to=settings.AUTH_USER_MODEL, verbose_name='Partagé par')),
            ],
            options={
                'verbose_name': 'Partage de document',
                'verbose_name_plural': 'Partages de documents',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Consultation'), ('download', 'Téléchargement'), ('share', 'Partage')], max_length=10, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document', verbose_name='Document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Accès document',
                'verbose_name_plural': 'Accès documents',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='document',
            name='linked_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='members.member', verbose_name='Membre lié'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Importé par'),
        ),
    ]
