# Generated by Django 4.2.27 on 2026-04-18 12:32

from django.db import migrations, models


def set_existing_docs_public(apps, schema_editor):
    """Préserver l'accès aux documents existants : tous en 'public' par défaut."""
    Document = apps.get_model('documents', 'Document')
    Document.objects.all().update(visibility='public')


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allowed_roles',
            field=models.CharField(blank=True, help_text='Liste de rôles (séparés par des virgules) si la visibilité est « Rôles spécifiques ».', max_length=255, verbose_name='Rôles autorisés'),
        ),
        migrations.AddField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('private', 'Personnel (seulement moi et les admins)'), ('staff', 'Équipe (pasteurs, anciens, diacres, secrétariat, finance, encadrants)'), ('roles', 'Rôles spécifiques (à choisir ci-dessous)'), ('public', 'Tout le monde (tous les utilisateurs connectés)')], default='staff', help_text='Qui peut voir et télécharger ce document.', max_length=10, verbose_name='Visibilité'),
        ),
        migrations.RunPython(set_existing_docs_public, reverse_noop),
    ]
