# Generated by Django 4.2.27 on 2026-04-18 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_add_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('kind', models.CharField(choices=[('compte_rendu', 'Compte-rendu de réunion'), ('courrier', 'Courrier officiel'), ('convocation', 'Convocation'), ('attestation', 'Attestation'), ('note_service', 'Note de service'), ('rapport', 'Rapport'), ('autre', 'Autre document')], default='courrier', max_length=20, verbose_name='Type de document')),
                ('reference', models.CharField(blank=True, help_text='Ex. : EEBC/CR/2026/04 (généré automatiquement si vide).', max_length=80, verbose_name='Référence')),
                ('document_date', models.DateField(verbose_name='Date du document')),
                ('recipient_name', models.CharField(blank=True, max_length=200, verbose_name='Destinataire')),
                ('recipient_address', models.TextField(blank=True, verbose_name='Adresse du destinataire')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Objet')),
                ('body_html', models.TextField(blank=True, verbose_name='Contenu')),
                ('signature_name', models.CharField(blank=True, max_length=120, verbose_name='Signataire')),
                ('signature_title', models.CharField(blank=True, max_length=160, verbose_name='Fonction du signataire')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('finalized', 'Finalisé')], default='draft', max_length=10, verbose_name='Statut')),
                ('visibility', models.CharField(choices=[('private', 'Personnel (seulement moi et les admins)'), ('staff', 'Équipe (pasteurs, anciens, diacres, secrétariat, finance, encadrants)'), ('roles', 'Rôles spécifiques (à choisir ci-dessous)'), ('public', 'Tout le monde (tous les utilisateurs connectés)')], default='staff', max_length=10, verbose_name='Visibilité')),
                ('allowed_roles', models.CharField(blank=True, max_length=255, verbose_name='Rôles autorisés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('generated_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_from', to='documents.document', verbose_name='Document PDF généré')),
            ],
            options={
                'verbose_name': 'Document généré',
                'verbose_name_plural': 'Documents générés',
                'ordering': ['-updated_at'],
            },
        ),
    ]
