# Generated by Django 4.2.27 on 2026-04-30

import apps.documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_generated_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=apps.documents.storage.DocumentStorage(), upload_to='documents/%Y/%m/', verbose_name='Fichier'),
        ),
    ]
