# Generated by Django 5.2.12 on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='kind',
            field=models.CharField(
                choices=[
                    ('compte_rendu', 'Compte-rendu de réunion'),
                    ('courrier', 'Courrier officiel'),
                    ('convocation', 'Convocation'),
                    ('invitation', 'Invitation'),
                    ('attestation', 'Attestation'),
                    ('note_service', 'Note de service'),
                    ('rapport', 'Rapport'),
                    ('autre', 'Autre document'),
                ],
                default='courrier',
                max_length=20,
                verbose_name='Type de document',
            ),
        ),
    ]