# Generated by Django 4.2.27 on 2025-12-31 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('group_type', models.CharField(choices=[('youth', 'Jeunesse'), ('choir', 'Chorale'), ('prayer', 'Groupe de prière'), ('study', "Groupe d'étude"), ('service', 'Service'), ('other', 'Autre')], default='other', max_length=15, verbose_name='Type')),
                ('meeting_day', models.CharField(blank=True, choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], max_length=15, verbose_name='Jour de réunion')),
                ('meeting_time', models.TimeField(blank=True, null=True, verbose_name='Heure de réunion')),
                ('meeting_location', models.CharField(blank=True, max_length=100, verbose_name='Lieu de réunion')),
                ('meeting_frequency', models.CharField(blank=True, choices=[('weekly', 'Hebdomadaire'), ('biweekly', 'Bihebdomadaire'), ('monthly', 'Mensuel')], max_length=20, verbose_name='Fréquence')),
                ('color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Couleur')),
                ('image', models.ImageField(blank=True, null=True, upload_to='groups/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='members.member', verbose_name='Membres')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Heure')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lieu')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='Sujet')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('attendees_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de participants')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Annulé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='groups.group', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
                'ordering': ['-date'],
            },
        ),
    ]
