# Generated by Django 6.0.2 on 2026-02-18 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_add_site_field'),
        ('members', '0004_lifeevent_lifeevent_date_idx_and_more'),
    ]

    operations = [
        # 1. Nullifier via SQL brut (la colonne s'appelle leader_id tant que la FK existe)
        migrations.RunSQL(
            sql="UPDATE groups_group SET leader_id = NULL WHERE leader_id IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 2. Changer la FK de User vers Member (tous les values sont NULL → pas d'IntegrityError)
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='led_groups',
                to='members.member',
                verbose_name='Responsable',
            ),
        ),
    ]
