# Generated by Django 4.2.27 on 2026-04-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_leader_fk_to_member'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='groupmeeting',
            index=models.Index(fields=['date'], name='grp_meeting_date_idx'),
        ),
    ]
