# Generated by Django 4.2.27 on 2025-12-31 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='Type de véhicule')),
                ('vehicle_model', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('license_plate', models.CharField(blank=True, max_length=20, verbose_name='Immatriculation')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='Capacité (passagers)')),
                ('zone', models.CharField(blank=True, help_text='Quartier ou zone géographique couverte', max_length=100, verbose_name='Zone desservie')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('available_sunday', models.BooleanField(default=True, verbose_name='Disponible le dimanche')),
                ('available_week', models.BooleanField(default=False, verbose_name='Disponible en semaine')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Chauffeur',
                'verbose_name_plural': 'Profils Chauffeurs',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=200, verbose_name='Demandeur')),
                ('requester_phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('pickup_address', models.TextField(verbose_name='Adresse de prise en charge')),
                ('event_date', models.DateField(verbose_name='Date')),
                ('event_time', models.TimeField(verbose_name='Heure')),
                ('event_name', models.CharField(blank=True, max_length=200, verbose_name='Événement')),
                ('passengers_count', models.PositiveIntegerField(default=1, verbose_name='Nombre de passagers')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('completed', 'Effectué'), ('cancelled', 'Annulé')], default='pending', max_length=15, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='transport.driverprofile', verbose_name='Chauffeur assigné')),
            ],
            options={
                'verbose_name': 'Demande de Transport',
                'verbose_name_plural': 'Demandes de Transport',
                'ordering': ['-event_date', '-event_time'],
            },
        ),
    ]
