# Generated by Django 5.2.9 on 2026-01-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du demandeur'),
        ),
    ]
