# Generated by Django 4.2.27 on 2026-04-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_transportrequest_requester_email'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['event_date', 'event_time'], name='trans_req_date_time_idx'),
        ),
    ]
