# Generated by Django 4.2.27 on 2026-05-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_transportrequest_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville de prise en charge'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='pickup_postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code postal de prise en charge'),
        ),
    ]
