# Generated by Django 5.2.17 on 2026-09-05 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_transportrequest_tracking_token'),
        ('young', '0003_youngmember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='requester_young',
            field=models.ForeignKey(blank=True, help_text='Lié automatiquement si le demandeur est connecté', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='young.youngmember', verbose_name='Jeune demandeur'),
        ),
    ]
