# Generated by Django 5.2.12 on 2026-04-03 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_newsarticle_article_pubdate_idx_and_more'),
        ('members', '0005_geocodedaddress'),
        ('transport', '0002_transportrequest_requester_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du groupe')),
                ('min_age', models.PositiveIntegerField(verbose_name='Âge minimum')),
                ('max_age', models.PositiveIntegerField(verbose_name='Âge maximum')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Groupe de jeunesse',
                'verbose_name_plural': 'Groupes de jeunesse',
                'ordering': ['min_age'],
            },
        ),
        migrations.CreateModel(
            name='YoungMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='young/photos/', verbose_name='Photo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('parent_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du parent / responsable légal')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone parent')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='Email parent')),
                ('emergency_contact', models.CharField(blank=True, max_length=200, verbose_name="Contact d'urgence")),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name="Téléphone d'urgence")),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('medical_notes', models.TextField(blank=True, verbose_name='Notes médicales')),
                ('is_baptized', models.BooleanField(default=False, verbose_name='Baptisé(e)')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='Date de baptême')),
                ('is_born_again', models.BooleanField(default=False, verbose_name='Né(e) de nouveau')),
                ('conversion_date', models.DateField(blank=True, null=True, verbose_name='Date de conversion')),
                ('needs_transport', models.BooleanField(default=False, verbose_name='Besoin de transport')),
                ('pickup_address', models.TextField(blank=True, verbose_name='Adresse de ramassage')),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('visiteur', 'Visiteur')], default='actif', max_length=15, verbose_name='Statut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_young', to='transport.driverprofile', verbose_name='Chauffeur assigné')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='young_members', to='core.family', verbose_name='Famille')),
                ('linked_member', models.OneToOneField(blank=True, help_text='Lier à une fiche membre existante (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='young_profile', to='members.member', verbose_name='Fiche membre liée')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='young_members', to='core.site', verbose_name='Site')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='young_members', to='young.youthgroup', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Jeune',
                'verbose_name_plural': 'Jeunes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='YouthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('event_type', models.CharField(choices=[('reunion', 'Réunion'), ('sortie', 'Sortie'), ('camp', 'Camp'), ('formation', 'Formation'), ('service', 'Service communautaire'), ('autre', 'Autre')], default='reunion', max_length=15, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Annulé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_youth_events', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youth_events', to='core.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Activité jeunesse',
                'verbose_name_plural': 'Activités jeunesse',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='YouthAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('excuse', 'Excusé'), ('retard', 'En retard')], default='absent', max_length=15, verbose_name='Statut')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('transported', models.BooleanField(default=False, verbose_name="Transporté par l'église")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_youth_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('young_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='young.youngmember', verbose_name='Jeune')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='young.youthevent', verbose_name='Activité')),
            ],
            options={
                'verbose_name': 'Présence jeunesse',
                'verbose_name_plural': 'Présences jeunesse',
                'ordering': ['young_member__last_name', 'young_member__first_name'],
                'unique_together': {('event', 'young_member')},
            },
        ),
        migrations.AddIndex(
            model_name='youngmember',
            index=models.Index(fields=['status'], name='young_young_status_b4fcad_idx'),
        ),
        migrations.AddIndex(
            model_name='youngmember',
            index=models.Index(fields=['site'], name='young_young_site_id_6f93c6_idx'),
        ),
        migrations.AddIndex(
            model_name='youngmember',
            index=models.Index(fields=['is_baptized'], name='young_young_is_bapt_360e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='youngmember',
            index=models.Index(fields=['group'], name='young_young_group_i_85ca89_idx'),
        ),
        migrations.AddIndex(
            model_name='youngmember',
            index=models.Index(fields=['last_name', 'first_name'], name='young_young_last_na_37a09c_idx'),
        ),
    ]
