# Generated by Django 4.2.27 on 2026-06-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('young', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='youthevent',
            index=models.Index(fields=['date'], name='youth_event_date_idx'),
        ),
    ]
