# Generated by Django 5.2.9 on 2026-01-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('template_type', models.CharField(choices=[('event_notification', "Notification d'événement"), ('event_reminder', "Rappel d'événement"), ('event_cancelled', 'Événement annulé'), ('transport_confirmation', 'Confirmation de transport'), ('welcome', 'Bienvenue'), ('password_reset', 'Réinitialisation mot de passe'), ('birthday', 'Anniversaire'), ('donation_receipt', 'Reçu de don'), ('custom', 'Personnalisé')], max_length=30, verbose_name='Type de template')),
                ('subject', models.CharField(help_text='Variables disponibles: {{event.title}}, {{recipient_name}}, {{site_name}}', max_length=200, verbose_name="Sujet de l'email")),
                ('html_content', models.TextField(help_text="Contenu HTML de l'email. Variables Django disponibles.", verbose_name='Contenu HTML')),
                ('text_content', models.TextField(blank=True, help_text="Version texte de l'email (optionnel, généré automatiquement si vide)", verbose_name='Contenu texte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, help_text='Un seul template par défaut par type', verbose_name='Template par défaut')),
                ('variables_help', models.TextField(blank=True, help_text='Documentation des variables disponibles pour ce template', verbose_name='Aide sur les variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Template d'email",
                'verbose_name_plural': "Templates d'emails",
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='template_type',
            field=models.CharField(blank=True, help_text='Type de template utilisé pour cet email', max_length=30, verbose_name='Type de template utilisé'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', '-created_at'], name='communicati_status_904a43_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient_email', '-created_at'], name='communicati_recipie_0cee88_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['template_type', '-created_at'], name='communicati_templat_6eb014_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('template_type', 'is_default')},
        ),
    ]
