# Generated by Django 5.2.9 on 2026-01-06 19:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_emailtemplate_emaillog_template_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('notification_type', models.CharField(choices=[('all', 'Toutes les notifications'), ('events', 'Événements'), ('worship', 'Cultes'), ('bibleclub', 'Club Biblique'), ('finance', 'Finance'), ('pastoral', 'Suivi pastoral'), ('administrative', 'Administratif')], max_length=20, verbose_name='Type de notification')),
                ('unsubscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribe_token', models.UUIDField(verbose_name='Token utilisé')),
            ],
            options={
                'verbose_name': 'Préférence de désabonnement',
                'verbose_name_plural': 'Préférences de désabonnement',
                'ordering': ['-unsubscribed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log email', 'verbose_name_plural': 'Logs emails'},
        ),
        migrations.RemoveIndex(
            model_name='emaillog',
            name='communicati_status_904a43_idx',
        ),
        migrations.RemoveIndex(
            model_name='emaillog',
            name='communicati_recipie_0cee88_idx',
        ),
        migrations.RemoveIndex(
            model_name='emaillog',
            name='communicati_templat_6eb014_idx',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='author',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='template_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='notify_by_email',
            field=models.BooleanField(default=False, verbose_name='Notifier par email'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='notify_by_sms',
            field=models.BooleanField(default=False, verbose_name='Notifier par SMS'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('members', 'Membres uniquement'), ('staff', 'Équipe uniquement')], default='public', max_length=10, verbose_name='Visibilité'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cliqué le'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ouvert le'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token de désabonnement'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Texte du lien'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, verbose_name="URL d'action"),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='cost_cents',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Coût (centimes)'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Délivré le'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name="Message d'erreur"),
        ),
        migrations.AddField(
            model_name='smslog',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID externe'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('bounced', 'Rejeté'), ('opened', 'Ouvert'), ('clicked', 'Cliqué')], default='pending', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('success', 'Succès'), ('error', 'Erreur')], default='info', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom destinataire'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='recipient_phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone destinataire'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('delivered', 'Délivré')], default='pending', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterUniqueTogether(
            name='unsubscribepreference',
            unique_together={('email', 'notification_type')},
        ),
    ]
