# Generated by Django 4.2.27 on 2026-04-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_add_is_pinned_to_announcement'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status'], name='comm_emaillog_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='comm_notif_user_read_idx'),
        ),
    ]
