# Generated by Django 4.2.27 on 2026-06-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_emaillog_comm_emaillog_status_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='comm_annonce_active_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['sent_at'], name='comm_emaillog_sent_at_idx'),
        ),
    ]
