# Generated by Django 4.2.27 on 2026-06-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_announcement_comm_annonce_active_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSenderDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du département')),
                ('from_email', models.EmailField(max_length=254, verbose_name="Adresse d'envoi")),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Département expéditeur',
                'verbose_name_plural': 'Départements expéditeurs',
                'ordering': ['order', 'name'],
            },
        ),
    ]
