# Generated by Django 5.2.9 on 2026-01-06 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('members', 'Membres'), ('children', 'Enfants')], max_length=20, verbose_name="Type d'import")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('success', 'Réussi'), ('error', 'Erreur'), ('partial', 'Partiel')], default='pending', max_length=20, verbose_name='Statut')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file_path', models.FileField(upload_to='imports/', verbose_name='Fichier')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Lignes totales')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='Lignes traitées')),
                ('success_rows', models.PositiveIntegerField(default=0, verbose_name='Lignes réussies')),
                ('error_rows', models.PositiveIntegerField(default=0, verbose_name='Lignes en erreur')),
                ('error_log', models.TextField(blank=True, verbose_name="Journal d'erreurs")),
                ('success_log', models.TextField(blank=True, verbose_name='Journal de succès')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Démarré à')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Importé par')),
            ],
            options={
                'verbose_name': "Journal d'import",
                'verbose_name_plural': "Journaux d'import",
                'ordering': ['-started_at'],
            },
        ),
    ]
