# Generated by Django 5.2.9 on 2026-01-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='import_type',
            field=models.CharField(choices=[('members', 'Membres'), ('children', 'Enfants'), ('export', 'Export')], max_length=20, verbose_name="Type d'import"),
        ),
    ]
