# Generated by Django 5.2.12 on 2026-04-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_alter_importlog_import_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='import_type',
            field=models.CharField(choices=[('members', 'Membres'), ('children', 'Enfants'), ('young_members', 'Jeunes'), ('export', 'Export')], max_length=20, verbose_name="Type d'import"),
        ),
    ]
