# Generated by Django 4.2.27 on 2026-05-05 11:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_add_young_members_import_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='file_path',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='imports/', verbose_name='Fichier'),
        ),
    ]
